// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFileStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptFileStep'](arg1, arg2, arg3);
}

export function EncryptFileStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptFileStep'](arg1, arg2, arg3);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
