// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EncryptFileStep(arg1:string,arg2:string,arg3:string,arg4:any):Promise<void>;

export function SelectFile():Promise<string>;
